[project]
name = "hotel-price-tracker"
version = "0.1.0"
description = ""
authors = [
    { name = "Maria-Minerva Vonica", email = "maria.minerva.vonica@gmail.com" }
]
dependencies = []

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = [
    "black>=23.0.0",
    "flake8>=6.0.0",
    "pytest>=7.0.0"
]